-- Basic config
require("core.mappings")
require("core.plugins")
require("core.colors")
require("core.configs")

-- Plugins config
require("plugins.telescope")
require("plugins.mason")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.lualine")
require("plugins.gitsigns")
-- require("plugins.treesitter")
require("plugins.toggleterm")
require("plugins.outline")
require("plugins.autopairs")
require("plugins.comments")
-- require("plugins.autotag")
require("plugins.buffline")
require("plugins.dashboard")
require("plugins.whichkey")
-- require("plugins.coc")
require("plugins.lazygit")
require("plugins.neotree")
require("plugins.neoscroll")
require("plugins.bqf")

-- Custom
require("plugins.config-opener")
require("plugins.system-explorer-opener")
